# Generated by Django 5.1.6 on 2025-06-28 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=1000)),
                ('result', models.CharField(default='', max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('probability', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star - Very Poor'), (2, '2 Stars - Poor'), (3, '3 Stars - Average'), (4, '4 Stars - Good'), (5, '5 Stars - Excellent')], help_text='User rating from 1 to 5 stars')),
                ('comment', models.TextField(blank=True, help_text='Optional user comment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='detection.detection')),
            ],
            options={
                'verbose_name': 'Detection Feedback',
                'verbose_name_plural': 'Detection Feedbacks',
            },
        ),
    ]
